// templates/vue/appkit/components/InfoList.vue
<template>
  <div class="info-list">
    <section>
      <h2>Wallet Information</h2>
      <pre>
Address: {{ accountInfo.address }}
CAIP Address: {{ accountInfo.caipAddress }}
Connected: {{ accountInfo.isConnected }}
Status: {{ accountInfo.status }}
Account Type: {{ accountInfo.embeddedWalletInfo?.accountType || 'N/A' }}
<template v-if="accountInfo.embeddedWalletInfo?.user?.email">Email: {{ accountInfo.embeddedWalletInfo.user.email }}</template>
<template v-if="accountInfo.embeddedWalletInfo?.user?.username">Username: {{ accountInfo.embeddedWalletInfo.user.username }}</template>
<template v-if="accountInfo.embeddedWalletInfo?.authProvider">Provider: {{ accountInfo.embeddedWalletInfo.authProvider }}</template>
      </pre>
    </section>

    <section>
      <h2>Theme</h2>
      <pre>
Theme Mode: {{ kitTheme.themeMode }}
      </pre>
    </section>

    <section>
      <h2>State</h2>
      <pre>
Selected Network ID: {{ state.selectedNetworkId || "None" }}
Loading: {{ state.loading }}
Modal Open: {{ state.open }}
      </pre>
    </section>

    <section>
      <h2>Wallet Info</h2>
      <pre>
Name: {{ walletInfo.walletInfo?.name || "N/A" }}
      </pre>
    </section>
  </div>
</template>

<script>
import { onMounted } from "vue";
import {
  useAppKitState,
  useAppKitTheme,
  useAppKitEvents,
  useAppKitAccount,
  useWalletInfo,
} from "@reown/appkit/vue";

export default {
  name: "InfoList",
  setup() {
    const kitTheme = useAppKitTheme();
    const state = useAppKitState();
    const accountInfo = useAppKitAccount();
    const events = useAppKitEvents();
    const walletInfo = useWalletInfo();

    onMounted(() => {
      console.log("Events: ", events);
    });

    return {
      kitTheme,
      state,
      accountInfo,
      walletInfo,
    };
  },
};
</script>

<style scoped>
.info-list {
  margin-top: 32px;
}

section {
  margin-bottom: 24px;
}

h2 {
  font-size: 18px;
  font-weight: bold;
  margin-bottom: 8px;
}

pre {
  background-color: #f3f4f6;
  padding: 16px;
  border-radius: 4px;
  overflow: auto;
  line-height: 1.5;
  font-size: 14px;
}
</style>

// templates/nextjs/app-router/components/InfoList.tsx
"use client";

import { useEffect } from "react";
import {
  useAppKitState,
  useAppKitTheme,
  useAppKitEvents,
  useAppKitAccount,
  useWalletInfo,
} from "@reown/appkit/react";
import { useClientMounted } from "@/hooks/useClientMount";

export const InfoList = () => {
  const kitTheme = useAppKitTheme();
  const state = useAppKitState();
  const { address, caipAddress, isConnected, embeddedWalletInfo } =
    useAppKitAccount();
  const events = useAppKitEvents();
  const walletInfo = useWalletInfo();
  const mounted = useClientMounted();

  useEffect(() => {
    console.log("Events: ", events);
  }, [events]);

  return !mounted ? null : (
    <>
      <section className='mt-8'>
        <h2 className='text-xl font-bold mb-2'>Wallet Information</h2>
        <pre className='bg-gray-100 p-4 rounded text-sm overflow-auto'>
          Address: {address}
          <br />
          CAIP Address: {caipAddress}
          <br />
          Connected: {isConnected.toString()}
          <br />
          Account Type: {embeddedWalletInfo?.accountType || "N/A"}
          <br />
          {embeddedWalletInfo?.user?.email &&
            `Email: ${embeddedWalletInfo.user.email}\n`}
          {embeddedWalletInfo?.user?.username &&
            `Username: ${embeddedWalletInfo.user.username}\n`}
          {embeddedWalletInfo?.authProvider &&
            `Provider: ${embeddedWalletInfo.authProvider}\n`}
        </pre>
      </section>

      <section className='mt-4'>
        <h2 className='text-xl font-bold mb-2'>Theme</h2>
        <pre className='bg-gray-100 p-4 rounded text-sm'>
          Theme Mode: {kitTheme.themeMode}
          <br />
        </pre>
      </section>

      <section className='mt-4'>
        <h2 className='text-xl font-bold mb-2'>State</h2>
        <pre className='bg-gray-100 p-4 rounded text-sm'>
          Selected Network ID: {state.selectedNetworkId?.toString() || "None"}
          <br />
          Loading: {state.loading.toString()}
          <br />
          Modal Open: {state.open.toString()}
          <br />
        </pre>
      </section>

      <section className='mt-4 mb-8'>
        <h2 className='text-xl font-bold mb-2'>Wallet Info</h2>
        <pre className='bg-gray-100 p-4 rounded text-sm'>
          Name: {walletInfo.walletInfo?.name || "N/A"}
          <br />
        </pre>
      </section>
    </>
  );
};
